M48
; DRILL file {KiCad (6.0.0)} date Thu Feb 10 18:09:31 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-10T18:09:31+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1181
%
G90
G05
T1
X7.7696Y-5.3458
T2
X7.8754Y-5.4516
T3
X4.8155Y-5.768
X4.8324Y-4.638
X6.0155Y-5.768
X6.0255Y-4.638
T0
M30
