M48
; DRILL file {KiCad (6.0.0)} date Thu Feb 10 17:28:02 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-10T17:28:02+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0413
%
G90
G05
T1
X7.7696Y-5.3458
T2
X7.8754Y-5.4516
T0
M30
